### ISSUE TITLE
Add codes for stacks and queues ! 

### ISSUE THREAD

**Issue by vsvipul** [vsvipul/DataStructures#1]
add simple code to implement stacks and queues.

**Comment by pradeepgangwar** [comment]
Which codes You want array based or structure based ?

**Comment by vsvipul** [comment]
@pradeepgangwar  whichever you wish to add u can, although the linked list implementation will be better.. Use proper indentation please.. Refer LinkedList.c ... Should i assign it to you ?

**Comment by pradeepgangwar** [comment]
I will add **stack** and **queue** array part for now and **linked list** implementation will be added later

**Comment by vsvipul** [comment]
ok .. add it . !

**Comment by vsvipul** [comment]
@pradeepgangwar  preferably add codes from the book Deepali Srivastava and add them to the root of the repository. !

**Comment by vsvipul** [comment]
@pradeepgangwar  @aswinzz  linked list implementation of stacks and queues needed !
