### ISSUE TITLE
Add lab 4 solutions 

### ISSUE THREAD

**Issue by vsvipul** [vsvipul/DataStructures#2]

**Comment by pradeepgangwar** [comment]
I will do it :)

**Comment by vsvipul** [comment]
there were 4 questions in lab 4 .. @aswinzz how much can u put up and which ones? @pradeepgangwar  how much can u put up and which ones ? ?

**Comment by aswinzz** [comment]
Q1 And Q2

**Comment by vsvipul** [comment]
ok @aswinzz  u add q1 and q2 @pradeepgangwar  u add q3 and q4 !

**Comment by vsvipul** [comment]
q4 is remaining @pradeepgangwar  @aswinzz  whoever can add do it ! send pr from now.. !
